### ISSUE TITLE
i have 500 error

### ISSUE THREAD

**Issue by CARocha** [NetAngels/django-fastcgi#1]
hi i don't know why error in bluehost shared hosting i run python 2.7.12 and django 1.9.7
i install django-fastcgi and flup very well, i think configure well but not working :( any help

---------- run ./myproyect.fcgi in console -------------------
 is good is response in console this
Status: 200 OK
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=utf-8

<!DOCTYPE html>
<html>
<head>
    <title>the base</title>
</head>
<body>

```
Hello
```

</body>
</html>
---------------------- end console -------------

but my .htaccess like this

-------------- .htaccesss ------------
AddHandler fcgid­-script .fcgi
# For security reasons, Option followsymlinks cannot be overridden.
# Options +FollowSymLinks

Options +SymLinksIfOwnerMatch
RewriteEngine On
RewriteBase /
RewriteRule ^(media/._)$ ­ [L]
RewriteRule ^(static/._)$ ­ [L]
RewriteRule ^(myproyect.fcgi/._)$ ­ [L]
RewriteRule ^(._)$ myproyect.fcgi/$1 [L]
-------------- end -----------------------

when i visit link in web browser i see the error
Internal Server Error
like .htaccess not access for myproyect.fcgi ?????

any idea, maybe see any problem or any question

thank any helps

**Comment by chukreev-alexey** [comment]
Try this .htaccess to make sure Django works:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ path-to-wrapper/django-wrapper.fcgi/$1 [QSA,L]

**Comment by CARocha** [comment]
Hi, it works like a charm

thank you!
