### ISSUE TITLE
Pipit

### ISSUE THREAD

**Issue by dmarcelino** [NetAngels/django-fastcgi#2]
Hi @chukreev-alexey, thanks for this, it's a lifesaver!

I've tried to find django-fastcgi in pypi and came across https://pypi.python.org/pypi/django-fastcgi/0.0.1 but doesn't seem to the same project (or it's outdated). Is django-fastcgi anywhere else in pypi?

Thanks

**Comment by mrts** [comment]
You can install it with `pip` as follows meanwhile:

```
pip install git+http://github.com/NetAngels/django-fastcgi.git
```

**Comment by peterdemin** [comment]
+1

**Comment by peterdemin** [comment]
Are you going to deploy to pypi?

**Comment by chukreev-alexey** [comment]
Soon we will deploy django-fastcgi to pypi.

**Comment by alurin** [comment]
At now, you can install this package from PyPI:

`pip install django-fastcgi-server`

Or how already suggested:

`pip install git+https://github.com/NetAngels/django-fastcgi.git@0.1`
